name: Audit only (develop branch)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Check for vulnerabilities
        run: npm audit --omit=dev --audit-level=high || true
